# Generated by Django 3.2.9 on 2021-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('reciver', models.CharField(max_length=100)),
                ('greeting_message', models.TextField()),
            ],
        ),
    ]
