# Generated by Django 3.2.9 on 2021-12-15 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_greeting_card_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting_card',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 15, 23, 37, 19, 912703)),
        ),
    ]
